datasources:
  zrodlopos:
    jdbcUrl: jdbc:mysql://176.31.127.202:3306/carpartscatalog
    username: car
    password: admin
    maximumPoolSize: 10
    liquibase:
      change-log: classpath:/db/changelog/zrodlo_pos/db.changelog-zrodloPos.xml
  zrodlopracownicy:
    jdbcUrl: jdbc:mysql://176.31.127.202:3306/carpartscatalog
    username: car
    password: admin
    maximumPoolSize: 10
    liquibase:
      change-log: classpath:/db/changelog/zrodlo_pracownicy/db.changelog-zrodloPracownicy.xml
---
